### ISSUE TITLE
Breadcrumb parts not working as links

### ISSUE THREAD

**Issue by teo1978** [arduino/reference-en#301]
For example at https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/indexof/

At the top (almost) of the page there's a breadcrumb like:
```    Reference > Language > Variables > Data types > String > Functions > Indexof ```

I'd expect to be able to click on "String" and see all the documentation about the String class, or whatever. Instead, the text "String" is not a link.

Some of the items in the path are links, but only up to "Variables"; the rest are not. There's no good reason for that.

**Comment by smellai** [comment]
Hi @teo1978 , you are totally right, we already have an issue in the proper repo, thanks
https://github.com/bcmi-labs/reference/issues/73

**Comment by teo1978** [comment]
Oh, I see. Do you have a working link to that?
Or is it a private repo or something?

**Comment by smellai** [comment]
It's private, I'll write something here too when fixed

**Comment by FalconFour** [comment]
Can I +1 this? This is quite a frustrating problem when trying to browse the reference pages. A lot of reference pages have this issue, or no breadcrumb trail at all...

Examples:
https://www.arduino.cc/reference/en/language/structure/bitwise-operators/bitwisexor/
https://www.arduino.cc/reference/en/language/functions/communication/serial/println/

Don't understand why this issue is "closed" as it's been broken this whole time...

**Comment by per1234** [comment]
@FalconFour I'm sorry to hear this limitation of the Arduino Language Reference is an inconvenience to you.

The reason the issue is closed is because this repository is only for the language reference content. There is no way for this issue to be fixed by changes to this repository. So, even though the issue is valid, it's off topic for this repository. There is a separate closed source repository that contains the code for generating the language reference from the content in this repository. It is in that repository that the changes could be made to fix the issue, so it is appropriate for the issue to be located in that repository, which it is.
