### ISSUE TITLE
arduino nano (ATMEGA328P) interrupt FALLING is doing CHANGE

### ISSUE THREAD

**Issue by jps2000** [arduino/reference-en#414]
Attaching interrupt to PD2 or PD3 should handle RISING, CHANGE and FALLING behavior.
However FALLING is actually doing CHANGE. RISING is working properly!

**Comment by per1234** [comment]
Is this really related to a problem with the documentation content?

**Comment by e-ika** [comment]
Yes, seems something that isn't working

**Comment by per1234** [comment]
I've been doing some experiments and I can't manage to reproduce this issue. `FALLING` is working just as expected for me.

I'm going to close this but if @jps2000 or @e-ika will provide me with enough information to reproduce the issue, I'll be happy to re-open it.

Note that if you use a switch or similar to trigger the interrupt, you could indeed get a `FALLING` interrupt when the pin goes `HIGH`. The reason is that contact bounce will actually cause several transitions from `HIGH` to `LOW` and back before the pin reaches a steady state. A more suitable source of a clean interrupt signal for testing is another Arduino board running the Blink example.
