### ISSUE TITLE
readStringUntil(): unclear whether including or not including delimiter

### ISSUE THREAD

**Issue by teo1978** [arduino/reference-en#446]
https://www.arduino.cc/en/Reference/StreamReadStringUntil

> readStringUntil() reads characters from a stream into a string. The function terminates if the terminator character is detected or it times out

> Returns
The entire string read from a stream, until the terminator character is detected

It is unclear whether the returned string includes the terminator or not.

I seem to understand it _is_ included; if that is the case, it could easily be stated more explicitly.

**Comment by per1234** [comment]
I'm merging in https://github.com/arduino/Arduino/issues/6137 because this is now the more appropriate place for that issue.

[*jzaruba commented on Mar 30, 2017*](https://github.com/arduino/Arduino/issues/6137#issue-218296291)
>https://www.arduino.cc/en/Serial/ReadStringUntil
It is not clear whether the returned value contains the terminator or not. (I read elsewhere that it does not.) And what happens to the terminator? Is it returned in the next Serial.read or is it thrown away?

---
[*inflector commented on Dec 5, 2017*](https://github.com/arduino/Arduino/issues/6137#issuecomment-349362032)
>From testing the code, the answer to this question is:
>1. It does NOT return the terminator.
>1. It does NOT leave it in the buffer and return it the next time.
