### ISSUE TITLE
Offline and online versions differing

### ISSUE THREAD

**Issue by brycecherry75** [arduino/reference-en#734]
I noted that the Language Reference in the offline version does not fully reflect the online version, so can I recommend addressing this issue including with each update of the Arduino IDE?

**Comment by per1234** [comment]
Thanks for the report @brycecherry75! I also have noticed this and reported it in the IDE repository: https://github.com/arduino/Arduino/issues/8860.

From looking at [the script that generates the bundled reference](https://github.com/arduino/Arduino/blob/master/build/create_reference.pl), it appears to me that there is nothing that needs to be done in this repository to fix the issue, so I think the arduino/Arduino repository is the more appropriate place to report this issue. Since we already have a report there, I'll go ahead and close this. If anyone wants to submit a pull request with an update to the script, I'm that would be very welcome and a great contribution to the Arduino project.
