### ISSUE TITLE
Link broken on Tone reference page

### ISSUE THREAD

**Issue by thearduinoguy** [arduino/reference-en#736]
https://www.arduino.cc/reference/en/language/functions/advanced-io/noTone

Generates error

**Comment by kengdahl** [comment]
This seems to be fixed unless I'm missing something.

**Comment by per1234** [comment]
You're right @kengdahl. Thanks for pointing that out!

It got a bit confusing because I merged a contributed PR to fix this rather than my own PR, which was configured to automatically close this issue.

Fixed by https://github.com/arduino/reference-en/pull/764
Thanks to @thearduinoguy for bringing this to our attention!
