### ISSUE TITLE
online arduino.cc documentation not generated from this repository

### ISSUE THREAD

**Issue by Semnodime** [arduino/reference-en#912]
Where is the [Adafruit GFX Library](https://www.arduino.cc/reference/en/libraries/tft/) **documentation** aka the document displayed on [the arduino reference guide](https://www.arduino.cc/reference/en/libraries/tft/) located?
I was hoping for it to be within this repository, to fix some formatting and references via PR.

Apparently, the arduino website is not generated from this github reference-en repository, right?
Guess that disencourages further collaboration….

**Comment by per1234** [comment]
Hi @Semnodime. Thanks for your interest in contributing to the Arduino Library Reference!

First of all, the links you shared are to the reference page of the "**TFT**" library, not the "**Adafruit GFX Library**".

Regarding the documentation of the "**TFT**" library, if you click the "**[Go to repository](https://github.com/arduino-libraries/TFT)**" link on that reference page, it takes you to the repository of the **TFT** library. The TFT library reference source content is stored in Markdown files in the `docs` subfolder of that repository. You are welcome to submit pull requests to that repository for any fixes. This repository is for the content of the Arduino Language Reference. It makes more sense to maintain the library reference content alongside the the source code in each library repository, since a change to the code may also require a change to the docs.

Regarding the documentation of the "**Adafruit GFX Library**", Arduino does generate a reference page for every library in the Arduino Library Manager, which includes "**Adafruit GFX Library**":

https://www.arduino.cc/reference/en/libraries/adafruit-gfx-library/

That library doesn't use the system that generates the more comprehensive reference content from the `docs` folder like the **TFT** library does. The source content for the "**Adafruit GFX Library**" reference page is the library metadata. You will find that metadata by clicking the the "**Read the documentation**" link to get to the library repository and then opening the `library.properties` file you find in the library.

Adafruit also maintains their own documentation content for that library, which is not hosted on arduino.cc. If you would like to contribute to that content on adafruit.com, check the instructions available for their documentation system.
